import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    background: #12343b;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "INCSIGHT";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }
        Row {
            LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                height: 35px;
                placeholder-text: "Enter Your Income";

            }
        }
        Row {
            Button {
                text: "Get Insight";
                primary: true;
                height: 35px;
            }
        }
    }
}
